(function () {
  const rows = [
    ["Moisés", ["Egito", "Faraó", "Mar Vermelho", "mandamentos", "cajado"], "personagens", "facil", "📜"],
    ["Abraão", ["promessa", "Isaque", "Sara", "aliança", "Ur"], "personagens", "facil", "⛺"],
    ["Sara", ["Abraão", "Isaque", "riso", "idade", "promessa"], "personagens", "media", "👵"],
    ["Noé", ["arca", "dilúvio", "animais", "chuva", "aliança"], "personagens", "facil", "🌈"],
    ["José do Egito", ["sonhos", "túnica", "irmãos", "prisão", "fome"], "personagens", "facil", "🌾"],
    ["Davi", ["Golias", "harpa", "rei", "Salmos", "funda"], "personagens", "facil", "👑"],
    ["Golias", ["gigante", "Davi", "pedra", "filisteu", "funda"], "personagens", "facil", "🛡️"],
    ["Ester", ["rainha", "Assuero", "Hamã", "judeus", "banquete"], "personagens", "media", "👑"],
    ["Rute", ["Noemi", "Boaz", "Moabe", "respigar", "lealdade"], "personagens", "media", "🌾"],
    ["Samuel", ["profeta", "Eli", "Saul", "Davi", "voz"], "personagens", "media", "👂"],
    ["Daniel", ["leões", "Babilônia", "sonhos", "fornalha", "oração"], "personagens", "facil", "🦁"],
    ["Elias", ["Carmelo", "fogo", "Baal", "corvos", "carruagem"], "personagens", "media", "🔥"],
    ["Eliseu", ["Elias", "manto", "Naamã", "azeite", "profeta"], "personagens", "dificil", "🕊️"],
    ["Maria", ["Jesus", "anjo", "Belém", "mãe", "Magnificat"], "personagens", "facil", "💙"],
    ["José", ["Maria", "carpinteiro", "sonho", "Belém", "Egito"], "personagens", "media", "🪚"],
    ["Criação", ["Gênesis", "seis dias", "Adão", "Eva", "jardim"], "historias", "facil", "🌍"],
    ["Dilúvio", ["Noé", "arca", "chuva", "animais", "arco-íris"], "historias", "facil", "🌧️"],
    ["Êxodo", ["Egito", "Moisés", "Faraó", "pragas", "deserto"], "historias", "facil", "🚶"],
    ["Queda de Jericó", ["muralhas", "trombetas", "Josué", "sete", "cidade"], "historias", "media", "🏰"],
    ["Torre de Babel", ["línguas", "cidade", "céu", "confusão", "Gênesis"], "historias", "facil", "🗼"],
    ["Nascimento de Jesus", ["Belém", "manjedoura", "Maria", "José", "pastores"], "historias", "facil", "⭐"],
    ["Crucificação", ["cruz", "Calvário", "pregos", "Jesus", "morte"], "historias", "facil", "✝️"],
    ["Ressurreição", ["túmulo", "terceiro dia", "pedra", "Jesus", "vivo"], "historias", "facil", "🌅"],
    ["Pentecostes", ["Espírito Santo", "línguas", "fogo", "Atos", "discípulos"], "historias", "media", "🔥"],
    ["Jonas e o peixe", ["Nínive", "mar", "tempestade", "três dias", "fuga"], "historias", "facil", "🐟"],
    ["Fornalha ardente", ["Sadraque", "Mesaque", "Abede-Nego", "fogo", "Babilônia"], "historias", "media", "🔥"],
    ["Cativeiro babilônico", ["exílio", "Jerusalém", "Babilônia", "Nabucodonosor", "templo"], "historias", "dificil", "⛓️"],
    ["Entrada triunfal", ["jumentinho", "ramos", "Hosana", "Jerusalém", "multidão"], "historias", "media", "🌿"],
    ["Última Ceia", ["pão", "vinho", "discípulos", "Judas", "mesa"], "historias", "facil", "🍞"],
    ["Arca de Noé", ["madeira", "animais", "dilúvio", "pares", "chuva"], "historias", "facil", "🚢"],
    ["Jerusalém", ["templo", "Davi", "cidade", "muralhas", "Sião"], "lugares", "facil", "🏛️"],
    ["Belém", ["Jesus", "nascimento", "Davi", "manjedoura", "estrela"], "lugares", "facil", "⭐"],
    ["Nazaré", ["Galileia", "Jesus", "Maria", "José", "cidade"], "lugares", "facil", "🏘️"],
    ["Egito", ["Faraó", "Moisés", "pragas", "escravidão", "Nilo"], "lugares", "facil", "🌊"],
    ["Canaã", ["promessa", "terra", "Israel", "leite", "mel"], "lugares", "media", "🍯"],
    ["Mar Vermelho", ["Moisés", "aberto", "Egito", "travessia", "Faraó"], "lugares", "facil", "🌊"],
    ["Monte Sinai", ["mandamentos", "Moisés", "trovão", "aliança", "deserto"], "lugares", "media", "⛰️"],
    ["Galileia", ["Jesus", "lago", "Nazaré", "discípulos", "pesca"], "lugares", "media", "🐟"],
    ["Samaria", ["mulher", "poço", "samaritano", "Jesus", "cidade"], "lugares", "media", "🏺"],
    ["Rio Jordão", ["batismo", "João Batista", "água", "travessia", "Israel"], "lugares", "facil", "💧"],
    ["Getsêmani", ["oração", "oliveiras", "Jesus", "discípulos", "prisão"], "lugares", "media", "🌳"],
    ["Calvário", ["cruz", "Gólgota", "Jesus", "morte", "monte"], "lugares", "facil", "✝️"],
    ["Éden", ["jardim", "Adão", "Eva", "serpente", "árvore"], "lugares", "facil", "🌿"],
    ["Babilônia", ["exílio", "Nabucodonosor", "Daniel", "torre", "império"], "lugares", "media", "🏙️"],
    ["Betânia", ["Lázaro", "Marta", "Maria", "Jesus", "aldeia"], "lugares", "dificil", "🏡"],
    ["Arca da Aliança", ["tábuas", "querubins", "templo", "santuário", "ouro"], "objetos", "media", "📦"],
    ["Maná", ["deserto", "pão", "céu", "Israel", "Moisés"], "objetos", "facil", "🍞"],
    ["Cajado de Moisés", ["serpente", "mar", "pragas", "pastor", "rocha"], "objetos", "facil", "🪄"],
    ["Trombetas de Jericó", ["muralhas", "Josué", "sete", "sacerdotes", "cidade"], "objetos", "media", "🎺"],
    ["Harpa de Davi", ["música", "Saul", "Salmos", "cordas", "rei"], "objetos", "media", "🎵"],
    ["Funda", ["Davi", "Golias", "pedra", "pastor", "gigante"], "objetos", "facil", "🪨"],
    ["Coroa", ["rei", "Davi", "Salomão", "ouro", "cabeça"], "objetos", "facil", "👑"],
    ["Cruz", ["Jesus", "Calvário", "madeira", "pregos", "salvação"], "objetos", "facil", "✝️"],
    ["Cálice", ["vinho", "ceia", "Jesus", "aliança", "mesa"], "objetos", "media", "🍷"],
    ["Pães e peixes", ["multiplicação", "multidão", "cestos", "menino", "milagre"], "objetos", "facil", "🥖"],
    ["Menorá", ["candelabro", "templo", "azeite", "luz", "sete"], "objetos", "dificil", "🕎"],
    ["Tábuas da Lei", ["mandamentos", "pedra", "Sinai", "Moisés", "aliança"], "objetos", "facil", "🪨"],
    ["Túnica colorida", ["José", "irmãos", "Jacó", "sonhos", "ciúme"], "objetos", "facil", "🥻"],
    ["Altar", ["sacrifício", "oferta", "templo", "fogo", "adoração"], "objetos", "media", "🧱"],
    ["Óleo da unção", ["rei", "sacerdote", "Samuel", "cabeça", "consagração"], "objetos", "dificil", "🫗"],
    ["Gênesis", ["criação", "Adão", "Abraão", "começo", "José"], "livros", "facil", "📖"],
    ["Êxodo", ["Moisés", "Egito", "Faraó", "deserto", "pragas"], "livros", "facil", "📖"],
    ["Salmos", ["Davi", "poesia", "louvor", "harpa", "oração"], "livros", "facil", "🎵"],
    ["Provérbios", ["sabedoria", "Salomão", "conselhos", "ditados", "prudência"], "livros", "media", "💡"],
    ["Isaías", ["profeta", "Messias", "servo", "Jerusalém", "visão"], "livros", "media", "📜"],
    ["Daniel", ["leões", "Babilônia", "sonhos", "fornalha", "profecia"], "livros", "facil", "📖"],
    ["Mateus", ["evangelho", "Jesus", "genealogia", "reino", "discípulo"], "livros", "facil", "📖"],
    ["Marcos", ["evangelho", "Jesus", "rápido", "Pedro", "milagres"], "livros", "media", "📖"],
    ["Lucas", ["evangelho", "médico", "parábolas", "Teófilo", "Jesus"], "livros", "media", "📖"],
    ["João", ["evangelho", "verbo", "amor", "sinais", "Jesus"], "livros", "facil", "📖"],
    ["Atos", ["apóstolos", "Pentecostes", "Paulo", "igreja", "viagens"], "livros", "media", "📖"],
    ["Romanos", ["Paulo", "fé", "graça", "carta", "justificação"], "livros", "dificil", "📨"],
    ["Apocalipse", ["visões", "João", "sete igrejas", "dragão", "fim"], "livros", "facil", "🐉"],
    ["Rute", ["Noemi", "Boaz", "Moabe", "colheita", "redenção"], "livros", "media", "📖"],
    ["Ester", ["rainha", "judeus", "Hamã", "banquete", "Pérsia"], "livros", "media", "📖"],
    ["Água em vinho", ["Caná", "casamento", "Jesus", "talhas", "milagre"], "milagres", "facil", "🍷"],
    ["Multiplicação dos pães", ["peixes", "multidão", "cestos", "cinco", "Jesus"], "milagres", "facil", "🥖"],
    ["Caminhar sobre as águas", ["Pedro", "barco", "vento", "mar", "Jesus"], "milagres", "facil", "🌊"],
    ["Cego de Jericó", ["Bartimeu", "visão", "mendigo", "cura", "Jesus"], "milagres", "facil", "👁️"],
    ["Lázaro ressuscitado", ["túmulo", "Betânia", "Marta", "Maria", "quatro dias"], "milagres", "facil", "🪦"],
    ["Cura do leproso", ["pele", "limpo", "Jesus", "sacerdote", "doença"], "milagres", "media", "✨"],
    ["Mar Vermelho aberto", ["Moisés", "Egito", "travessia", "águas", "Faraó"], "milagres", "facil", "🌊"],
    ["Maná no deserto", ["Israel", "pão", "céu", "codornizes", "fome"], "milagres", "facil", "🍞"],
    ["Sol parou", ["Josué", "batalha", "Gibeão", "dia", "lua"], "milagres", "dificil", "☀️"],
    ["Fogo do céu", ["Elias", "Carmelo", "Baal", "altar", "profetas"], "milagres", "media", "🔥"],
    ["Naamã curado", ["lepra", "Jordão", "Eliseu", "sete mergulhos", "Síria"], "milagres", "media", "💧"],
    ["Tempestade acalmada", ["barco", "vento", "mar", "discípulos", "Jesus"], "milagres", "facil", "⛈️"],
    ["Filha de Jairo", ["menina", "morte", "Jesus", "sinagoga", "levanta"], "milagres", "media", "👧"],
    ["Pesca maravilhosa", ["redes", "Pedro", "barco", "peixes", "Jesus"], "milagres", "facil", "🎣"],
    ["Línguas de fogo", ["Pentecostes", "Espírito Santo", "Atos", "discípulos", "idiomas"], "milagres", "media", "🔥"],
    ["Filho Pródigo", ["pai", "porcos", "herança", "irmão", "volta"], "parabolas", "facil", "🏠"],
    ["Semeador", ["sementes", "solo", "espinhos", "pedras", "fruto"], "parabolas", "facil", "🌱"],
    ["Ovelha Perdida", ["pastor", "noventa e nove", "rebanho", "achar", "alegria"], "parabolas", "facil", "🐑"],
    ["Bom Samaritano", ["ferido", "estrada", "Jericó", "sacerdote", "próximo"], "parabolas", "facil", "🩹"],
    ["Dez Virgens", ["lâmpadas", "azeite", "noivo", "prudentes", "tardou"], "parabolas", "media", "🪔"],
    ["Talentos", ["servos", "dinheiro", "senhor", "enterrar", "multiplicar"], "parabolas", "facil", "💰"],
    ["Grão de Mostarda", ["semente", "pequeno", "árvore", "reino", "crescer"], "parabolas", "media", "🌿"],
    ["Joio e Trigo", ["campo", "inimigo", "colheita", "separar", "plantação"], "parabolas", "media", "🌾"],
    ["Rico e Lázaro", ["mendigo", "banquete", "Abraão", "tormento", "porta"], "parabolas", "dificil", "🍽️"],
    ["Fariseu e Publicano", ["oração", "templo", "humilde", "orgulho", "pecador"], "parabolas", "media", "🙏"],
    ["Grande Banquete", ["convite", "mesa", "desculpas", "servos", "festa"], "parabolas", "media", "🍽️"],
    ["Pérola de Grande Valor", ["comerciante", "vender", "tesouro", "reino", "preciosa"], "parabolas", "dificil", "🦪"],
    ["Tesouro Escondido", ["campo", "achou", "comprou", "alegria", "reino"], "parabolas", "media", "🪙"],
    ["Trabalhadores da vinha", ["salário", "dia", "dono", "últimos", "denário"], "parabolas", "dificil", "🍇"],
    ["Servo impiedoso", ["dívida", "perdão", "rei", "companheiro", "prisão"], "parabolas", "dificil", "⛓️"],
    ["Isaías", ["visão", "templo", "serafins", "Messias", "profeta"], "profetas", "media", "📜"],
    ["Jeremias", ["lágrimas", "exílio", "barro", "Judá", "nova aliança"], "profetas", "dificil", "📜"],
    ["Ezequiel", ["ossos secos", "roda", "exílio", "visões", "profeta"], "profetas", "dificil", "🦴"],
    ["Daniel", ["leões", "Babilônia", "sonhos", "estátua", "profeta"], "profetas", "facil", "🦁"],
    ["Jonas", ["Nínive", "peixe", "fuga", "tempestade", "arrependimento"], "profetas", "facil", "🐟"],
    ["Amós", ["justiça", "pastor", "Israel", "Tekoa", "juízo"], "profetas", "dificil", "⚖️"],
    ["Oséias", ["Gômer", "amor", "Israel", "infidelidade", "aliança"], "profetas", "dificil", "💔"],
    ["Joel", ["gafanhotos", "Espírito", "derramar", "dia do Senhor", "profeta"], "profetas", "dificil", "🦗"],
    ["Miqueias", ["Belém", "justiça", "humildade", "profeta", "governante"], "profetas", "dificil", "⚖️"],
    ["Naum", ["Nínive", "queda", "Assíria", "juízo", "profeta"], "profetas", "dificil", "🏙️"],
    ["Habacuque", ["fé", "justo", "queixa", "Babilônia", "profeta"], "profetas", "dificil", "❓"],
    ["Sofonias", ["dia do Senhor", "Judá", "juízo", "resto", "profeta"], "profetas", "dificil", "📣"],
    ["Ageu", ["templo", "reconstrução", "Zorobabel", "povo", "profeta"], "profetas", "dificil", "🧱"],
    ["Zacarias", ["visões", "templo", "Messias", "jumento", "profeta"], "profetas", "dificil", "🌿"],
    ["Malaquias", ["dízimos", "mensageiro", "aliança", "Elias", "profeta"], "profetas", "dificil", "📨"],
    ["Saul", ["Samuel", "primeiro", "rei", "Davi", "ciúme"], "reis", "media", "👑"],
    ["Davi", ["Jerusalém", "Golias", "Salmos", "Bate-Seba", "rei"], "reis", "facil", "👑"],
    ["Salomão", ["sabedoria", "templo", "provérbios", "riqueza", "rainha"], "reis", "facil", "👑"],
    ["Roboão", ["Salomão", "divisão", "Judá", "conselho", "impostos"], "reis", "dificil", "👑"],
    ["Jeroboão", ["Israel", "bezerros", "reino norte", "altar", "divisão"], "reis", "dificil", "👑"],
    ["Acabe", ["Jezabel", "Elias", "Baal", "vinha", "Samaria"], "reis", "media", "👑"],
    ["Ezequias", ["oração", "Assíria", "Isaías", "túnel", "reforma"], "reis", "dificil", "👑"],
    ["Josias", ["lei", "templo", "reforma", "Judá", "jovem"], "reis", "dificil", "👑"],
    ["Nabucodonosor", ["Babilônia", "Daniel", "estátua", "fornalha", "exílio"], "reis", "media", "👑"],
    ["Herodes", ["Jesus", "magos", "Belém", "templo", "rei"], "reis", "media", "👑"],
    ["Faraó", ["Egito", "Moisés", "pragas", "Êxodo", "coração duro"], "reis", "facil", "👑"],
    ["Ciro", ["Pérsia", "decreto", "templo", "exílio", "retorno"], "reis", "dificil", "👑"],
    ["Belsazar", ["banquete", "parede", "Daniel", "Babilônia", "escrita"], "reis", "dificil", "👑"],
    ["Jeosafá", ["Judá", "louvor", "batalha", "aliança", "rei"], "reis", "dificil", "👑"],
    ["Manassés", ["Judá", "ídolos", "arrependimento", "cativeiro", "rei"], "reis", "dificil", "👑"],
    ["Pedro", ["pescador", "negação", "rocha", "chaves", "apóstolo"], "apostolos", "facil", "🎣"],
    ["João", ["amor", "evangelho", "Apocalipse", "discípulo", "ilha"], "apostolos", "facil", "❤️"],
    ["Tiago", ["Zebedeu", "João", "Herodes", "apóstolo", "martírio"], "apostolos", "media", "⚡"],
    ["André", ["Pedro", "pescador", "primeiro", "irmão", "apóstolo"], "apostolos", "media", "🎣"],
    ["Filipe", ["Natanael", "gregos", "Jesus", "apóstolo", "segue-me"], "apostolos", "media", "👣"],
    ["Bartolomeu", ["Natanael", "figueira", "apóstolo", "Israelita", "Filipe"], "apostolos", "dificil", "🌳"],
    ["Tomé", ["dúvida", "dedo", "ressurreição", "Senhor", "apóstolo"], "apostolos", "facil", "✋"],
    ["Mateus", ["publicano", "imposto", "evangelho", "Levi", "apóstolo"], "apostolos", "media", "💰"],
    ["Simão Zelote", ["cananeu", "apóstolo", "grupo", "Jesus", "discípulo"], "apostolos", "dificil", "🔥"],
    ["Judas Tadeu", ["Lebeu", "apóstolo", "pergunta", "Jesus", "discípulo"], "apostolos", "dificil", "❔"],
    ["Judas Iscariotes", ["traição", "moedas", "beijo", "Jesus", "discípulo"], "apostolos", "facil", "💰"],
    ["Matias", ["sorteio", "substituto", "Judas", "Atos", "apóstolo"], "apostolos", "dificil", "🎲"],
    ["Paulo", ["Saulo", "Damasco", "cartas", "gentios", "viagens"], "apostolos", "facil", "📨"],
    ["Barnabé", ["Paulo", "encorajamento", "Antioquia", "Marcos", "viagem"], "apostolos", "dificil", "🤝"],
    ["Tiago filho de Alfeu", ["apóstolo", "menor", "discípulo", "lista", "Jesus"], "apostolos", "dificil", "📜"]
  ];

  window.CARDS_BIBLIA = rows.map((row, index) => ({
    id: `biblia-${String(index + 1).padStart(3, "0")}`,
    palavra: row[0],
    proibidas: row[1],
    categoria: row[2],
    dificuldade: row[3],
    emoji: row[4]
  }));
})();
